"""Cambion en las tablas de la base de datos

Revision ID: 2dc478e78f73
Revises: 29fffd879547
Create Date: 2025-11-24 02:43:13.636609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc478e78f73'
down_revision: Union[str, Sequence[str], None] = '29fffd879547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_per_unit', sa.Float(), nullable=False))
    op.add_column('order_items', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'), nullable=False))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    op.drop_column('orders', 'status')
    op.drop_column('order_items', 'discount')
    op.drop_column('order_items', 'price_per_unit')
    # ### end Alembic commands ###
